version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_gateway
    ports:
      - "80:80" # Dış dünyaya SADECE 80 portu (varsayılan HTTP) açık!
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - auth_network # Diğer projelerinle aynı ağa bağladık

networks:
  auth_network:
    external: true